openapi: 3.0.0
info:
  description: areg
  version: 0.1.0
  title: areg
  contact:
    email: cloudharness@metacell.us
  license:
    name: UNLICENSED
tags:
- name: test
paths:
  /ping:
    get:
      summary: Test the application is up
      operationId: ping
      tags:
      - test
      responses:
        '500':
          description: This shouldn't happen
        '200':
          description: What we want
          content:
            application/json:
              schema:
                type: string
      security: []
  /live:
    get:
      summary: Test if application is healthy
      operationId: live
      tags:
      - test
      responses:
        '500':
          description: Application is not healthy
        '200':
          description: Healthy
          content:
            application/json:
              schema:
                type: string
      security: []
  /ready:
    get:
      summary: Test if application is ready
      operationId: ready
      tags:
      - test
      responses:
        '500':
          description: Application is not ready
        '200':
          description: Ready
          content:
            application/json:
              schema:
                type: string
      security: []
servers:
- url: /api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: cloudharness.auth.decode_token
  schemas:
    Valid:
      type: object
      properties:
        response:
          type: string
