harness:
  subdomain: areg
  secured: false
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    port: 8080
  livenessProbe:
    path: /api/live
  readinessProbe:
    path: /api/ready
  dependencies:
    build:
    - cloudharness-frontend-build
    - cloudharness-django
    hard:
    - common
    - accounts
    - events
  use_services:
  - name: common
  database:
    auto: true
    type: postgres
