harness:
  subdomain: www
  secured: open
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    port: 8080
  livenessProbe:
    path: /api/live
  readinessProbe:
    path: /api/ready
  dependencies:
    build:
    - cloudharness-frontend-build
    - cloudharness-django
    hard:
    - common
    - events
    - accounts
  use_services:
  - name: common
  uri_role_mapping:
  - uri: /admin/*
    roles:
    - administrator
    - areg_portal:administrator
    - areg_portal:manager
    require-any-role: true
  - uri: /submit
    roles:
    - administrator
    - areg_portal:administrator
    - areg_portal:manager
    - areg_portal:user
    require-any-role: true
  - uri: /login
    roles: []
    require-any-role: true
  - uri: /
    white-listed: true

  database:
    auto: true
    type: postgres
  accounts:
    roles:
    - areg_portal:administrator
    - areg_portal:manager
    - areg_portal:user
