apiVersion: v1
appVersion: "1.0.0"
description: Antibody Registry Helm Chart
name: areg
version: 1.0.0
maintainers:
  - name: Filippo Ledda
    email: filippo@metacell.us
  - name: Zoran Sinnema
    email: zoran@metacell.us