apiVersion: v1
appVersion: 0.0.1
description: Areg Helm Chart
name: areg
version: 0.0.1
maintainers:
- email: zoran@metacell.us
  name: Zoran Sinnema
metadata:
  name: areg
  namespace: areg
  labels:
    app.kubernetes.io/managed-by: Helm
