local: true
secured_gatekeepers: true
domain: areg.local
namespace: areg
mainapp: accounts
registry:
  name: ''
  secret: ''
tag: latest
apps:
  areg:
    harness:
      subdomain: areg
      aliases: []
      domain: null
      dependencies:
        hard:
        - common
        - accounts
        - events
        soft: []
        build:
        - cloudharness-django
      secured: false
      uri_role_mapping:
      - uri: /*
        roles:
        - administrator
      deployment:
        auto: true
        replicas: 1
        image: cloudharness/areg:latest
        name: areg
        port: 8080
        resources: &id001
          requests:
            memory: 32Mi
            cpu: 10m
          limits:
            memory: 500Mi
            cpu: 500m
      service:
        auto: true
        name: areg
        port: 8080
      secrets: null
      use_services: []
      database:
        auto: false
        name: areg-db
        type: null
        size: 1Gi
        user: mnp
        pass: metacell
        image_ref: null
        mongo:
          image: mongo:5
          ports:
          - name: http
            port: 27017
        postgres:
          image: postgres:13
          initialdb: cloudharness
          ports:
          - name: http
            port: 5432
        neo4j:
          image: neo4j:4.1.9
          memory:
            size: 256M
            pagecache:
              size: 64M
            heap:
              initial: 64M
              max: 128M
          dbms_security_auth_enabled: 'false'
          ports:
          - name: http
            port: 7474
          - name: bolt
            port: 7687
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 1000m
      livenessProbe:
        path: /api/live
      readinessProbe:
        path: /api/ready
      name: areg
    image: cloudharness/areg:latest
    task-images: {}
    name: areg
    port: 8080
    resources: *id001
env:
- name: CH_VERSION
  value: 0.0.1
- name: CH_CHART_VERSION
  value: 0.0.1
- name: CH_AREG_SUBDOMAIN
  value: areg
- name: CH_AREG_NAME
  value: areg
- name: CH_DOMAIN
  value: areg.local
- name: CH_IMAGE_REGISTRY
  value: ''
- name: CH_IMAGE_TAG
  value: latest
privenv:
- name: CH_SECRET
  value: "In God we trust; all others must bring data. \u2015 W. Edwards Deming"
ingress:
  enabled: true
  name: cloudharness-ingress
  ssl_redirect: false
  letsencrypt:
    email: filippo@metacell.us
backup:
  active: true
  keep_days: '7'
  keep_weeks: '4'
  keep_months: '6'
  schedule: '*/5 * * * *'
  suffix: .gz
  volumesize: 2Gi
  dir: /backups
  resources:
    requests:
      memory: 32Mi
      cpu: 25m
    limits:
      memory: 64Mi
      cpu: 50m
name: cloudharness
task-images: {}
tls: false
localIp: 192.168.49.2
