local: true
secured_gatekeepers: true
domain: areg.local
namespace: areg
mainapp: areg-portal
registry:
  name: ''
  secret: ''
tag: latest
apps:
  accounts:
    harness:
      subdomain: accounts
      aliases: []
      domain: null
      dependencies:
        hard: []
        soft: []
        build: []
      secured: false
      uri_role_mapping:
      - uri: /*
        roles:
        - administrator
      deployment:
        auto: true
        replicas: 1
        image: areg/accounts:latest
        name: accounts
        port: 8080
        resources: &id001
          requests:
            memory: 512Mi
            cpu: 10m
          limits:
            memory: 1024Mi
            cpu: 500m
      service:
        auto: true
        name: accounts
        port: 8080
      secrets:
        api_user_password: ''
      use_services: []
      database:
        auto: true
        name: keycloak-postgres
        type: postgres
        size: 2Gi
        user: user
        pass: password
        image_ref: null
        mongo:
          image: mongo:5
          ports:
          - name: http
            port: 27017
        postgres:
          image: postgres:10.4
          initialdb: auth_db
          ports:
          - name: http
            port: 5432
        neo4j:
          image: neo4j:4.1.9
          memory:
            size: 256M
            pagecache:
              size: 64M
            heap:
              initial: 64M
              max: 128M
          dbms_security_auth_enabled: 'false'
          ports:
          - name: http
            port: 7474
          - name: bolt
            port: 7687
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 1000m
      env:
      - name: KEYCLOAK_IMPORT
        value: /tmp/realm.json
      - name: KEYCLOAK_USER
        value: admin
      - name: KEYCLOAK_PASSWORD
        value: metacell
      - name: PROXY_ADDRESS_FORWARDING
        value: 'true'
      - name: DB_VENDOR
        value: POSTGRES
      - name: DB_ADDR
        value: keycloak-postgres
      - name: DB_DATABASE
        value: auth_db
      - name: DB_USER
        value: user
      - name: DB_PASSWORD
        value: password
      - name: JAVA_OPTS
        value: -server -Xms64m -Xmx896m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m
          -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman
          -Djava.awt.headless=true  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED
          --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED
      resources:
      - name: realm-config
        src: realm.json
        dst: /tmp/realm.json
      readinessProbe:
        path: /auth/realms/master
      name: accounts
    client:
      id: rest-client
      secret: 5678eb6e-9e2c-4ee5-bd54-34e7411339e8
    webclient:
      id: web-client
      secret: 452952ae-922c-4766-b912-7b106271e34b
    enabled: true
    harvest: true
    admin:
      pass: metacell
      user: admin
      role: administrator
    image: areg/accounts:latest
    task-images: {}
    name: accounts
    port: 8080
    resources: *id001
  events:
    harness:
      subdomain: events
      aliases: []
      domain: null
      dependencies:
        hard: []
        soft: []
        build: []
      secured: true
      uri_role_mapping:
      - uri: /*
        roles:
        - administrator
      deployment:
        auto: true
        replicas: 1
        image: areg/events:latest
        name: events
        port: 9000
        resources: &id002
          requests:
            memory: 32Mi
            cpu: 10m
          limits:
            memory: 500Mi
            cpu: 500m
      service:
        auto: true
        name: events
        port: 80
      secrets: null
      use_services: []
      database:
        auto: false
        name: events-db
        type: null
        size: 1Gi
        user: mnp
        pass: metacell
        image_ref: null
        mongo:
          image: mongo:5
          ports:
          - name: http
            port: 27017
        postgres:
          image: postgres:13
          initialdb: cloudharness
          ports:
          - name: http
            port: 5432
        neo4j:
          image: neo4j:4.1.9
          memory:
            size: 256M
            pagecache:
              size: 64M
            heap:
              initial: 64M
              max: 128M
          dbms_security_auth_enabled: 'false'
          ports:
          - name: http
            port: 7474
          - name: bolt
            port: 7687
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 1000m
      env:
      - name: ZK_HOSTS
        value: zookeeper:2181
      name: events
    kafka:
      name: bootstrap
      port: 9092
      storage: 10Gi
      resources:
        limits:
          cpu: 500m
          memory: 600Mi
        requests:
          cpu: 50m
          memory: 100Mi
    pzoo:
      storage: 1Gi
      resources:
        limits:
          memory: 500Mi
        requests:
          cpu: 10m
          memory: 100Mi
    zoo:
      storage: 1Gi
      resources:
        limits:
          memory: 500Mi
        requests:
          cpu: 10m
          memory: 100Mi
    image: areg/events:latest
    task-images: {}
    name: events
    port: 9000
    resources: *id002
  common:
    harness:
      subdomain: common
      aliases: []
      domain: null
      dependencies:
        hard: []
        soft: []
        build:
        - cloudharness-flask
      secured: false
      uri_role_mapping:
      - uri: /*
        roles:
        - administrator
      deployment:
        auto: true
        replicas: 1
        image: areg/common:latest
        name: common
        port: 8080
        resources: &id003
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 200m
      service:
        auto: true
        name: common
        port: 8080
      secrets: null
      use_services: []
      database:
        auto: false
        name: common-db
        type: null
        size: 1Gi
        user: mnp
        pass: metacell
        image_ref: null
        mongo:
          image: mongo:5
          ports:
          - name: http
            port: 27017
        postgres:
          image: postgres:13
          initialdb: cloudharness
          ports:
          - name: http
            port: 5432
        neo4j:
          image: neo4j:4.1.9
          memory:
            size: 256M
            pagecache:
              size: 64M
            heap:
              initial: 64M
              max: 128M
          dbms_security_auth_enabled: 'false'
          ports:
          - name: http
            port: 7474
          - name: bolt
            port: 7687
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 1000m
      name: common
    image: areg/common:latest
    task-images:
      cloudharness-flask: areg/cloudharness-flask:latest
    name: common
    port: 8080
    resources: *id003
  areg_portal:
    harness:
      subdomain: areg-portal
      aliases: []
      domain: null
      dependencies:
        hard:
        - common
        - accounts
        - events
        soft: []
        build:
        - cloudharness-frontend-build
        - cloudharness-django
      secured: true
      uri_role_mapping:
      - uri: /*
        roles:
        - areg_portal:areg_portal-administrator
        - areg_portal:areg_portal-manager
        - areg_portal:areg_portal-user
        require-any-role: true
      deployment:
        auto: true
        replicas: 1
        image: areg/areg-portal:latest
        name: areg-portal
        port: 8080
        resources: &id004
          requests:
            memory: 32Mi
            cpu: 10m
          limits:
            memory: 500Mi
            cpu: 500m
      service:
        auto: true
        name: areg-portal
        port: 8080
      secrets: null
      use_services:
      - name: common
      database:
        auto: true
        name: areg-portal-db
        type: postgres
        size: 1Gi
        user: mnp
        pass: metacell
        image_ref: null
        mongo:
          image: mongo:5
          ports:
          - name: http
            port: 27017
        postgres:
          image: postgres:13
          initialdb: cloudharness
          ports:
          - name: http
            port: 5432
        neo4j:
          image: neo4j:4.1.9
          memory:
            size: 256M
            pagecache:
              size: 64M
            heap:
              initial: 64M
              max: 128M
          dbms_security_auth_enabled: 'false'
          ports:
          - name: http
            port: 7474
          - name: bolt
            port: 7687
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 1000m
      livenessProbe:
        path: /api/live
      readinessProbe:
        path: /api/ready
      name: areg-portal
    image: areg/areg-portal:latest
    task-images:
      cloudharness-frontend-build: areg/cloudharness-frontend-build:latest
      cloudharness-django: areg/cloudharness-django:latest
    name: areg-portal
    port: 8080
    resources: *id004
env:
- name: CH_VERSION
  value: 0.0.1
- name: CH_CHART_VERSION
  value: 0.0.1
- name: CH_ACCOUNTS_SUBDOMAIN
  value: accounts
- name: CH_ACCOUNTS_NAME
  value: accounts
- name: CH_EVENTS_SUBDOMAIN
  value: events
- name: CH_EVENTS_NAME
  value: events
- name: CH_COMMON_SUBDOMAIN
  value: common
- name: CH_COMMON_NAME
  value: common
- name: CH_AREG_PORTAL_SUBDOMAIN
  value: areg-portal
- name: CH_AREG_PORTAL_NAME
  value: areg-portal
- name: CH_DOMAIN
  value: areg.local
- name: CH_IMAGE_REGISTRY
  value: ''
- name: CH_IMAGE_TAG
  value: latest
privenv:
- name: CH_SECRET
  value: "In God we trust; all others must bring data. \u2015 W. Edwards Deming"
ingress:
  enabled: true
  name: cloudharness-ingress
  ssl_redirect: false
  letsencrypt:
    email: filippo@metacell.us
backup:
  active: false
  keep_days: '7'
  keep_weeks: '4'
  keep_months: '6'
  schedule: '*/5 * * * *'
  suffix: .gz
  volumesize: 2Gi
  dir: /backups
  resources:
    requests:
      memory: 32Mi
      cpu: 25m
    limits:
      memory: 64Mi
      cpu: 50m
name: areg
tls: false
task-images:
  cloudharness-flask: areg/cloudharness-flask:latest
  cloudharness-frontend-build: areg/cloudharness-frontend-build:latest
  cloudharness-django: areg/cloudharness-django:latest
  cloudharness-base: areg/cloudharness-base:latest
localIp: 192.168.49.2
