harness:
  sentry: false
  database:
    auto: true
    type: postgres
    size: 10Gi
  deployment:
    replicas: 1
  
  accounts:
    roles:
      - portal:administrator
      - portal:manager
    users:
      - username: admin
        email: admin@testuser.com
        realmRoles:
          - administrator
        clientRoles:
          - administrator
          - portal:administrator
      - username: manager
        email: manager@testuser.com
        clientRoles:
          - manager
          - portal:manager
