harness:
  subdomain: www
  secured: open
  sentry: true
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    replicas: 2
    port: 8080
    resources:
      requests:
        memory: 0.9Gi
        cpu: 50m
      limits:
        cpu: 4
        memory: 2Gi
    volume:
      name: areg-persistent-files
      mountpath: /usr/src/app/persistent
      auto: true
      size: 5Gi
      usenfs: false
  livenessProbe:
    path: /api/live
  readinessProbe:
    path: /api/ready
  envmap:
    WORKERS: 2
  dependencies:
    build:
      - cloudharness-django
    hard:
      - common
      - events
      - accounts
      - argo
    soft:
      - pgadmin
      - accounts-api
  use_services:
    - name: common
    - name: accounts_api
  uri_role_mapping:
    - uri: /admin/*
      roles:
        - administrator
    - uri: /api/antibodies/export
      roles: []
    - uri: /admin
      roles:
        - administrator
      require-any-role: true
    - uri: /add
      roles: []
      require-any-role: true
    - uri: /submissions
      roles: []
      require-any-role: false
    - uri: /login
      roles: []
      require-any-role: true
    - uri: /
      white-listed: true
    - uri: /metrics
      roles:
        - administrator

  database:
    auto: true
    type: postgres
    size: 40Gi
    postgres:
      image: postgres:13
      initialdb: antibody_registry
    resources:
      requests:
        memory: 1Gi
        cpu: 50m
      limits:
        memory: 4Gi
  accounts:
    roles:
      - administrator
      - manager
      - user
  test:
    e2e:
      smoketest: false
      enabled: true
  secrets:
    scicrunch-api-key: 

export_query: "SELECT 'AB_' || ab_id as rrid, ab_name, catalog_num, cat_alt, api_vendor.vendor as vendor_name, api_vendor.vendor || ' Cat# ' || catalog_num || ', RRID:AB_' || ab_id AS proper_citation from api_antibody LEFT JOIN api_vendor on api_vendor.id = vendor_id WHERE true"
export_all_fields_query: "WITH applications_subquery AS (SELECT ix, string_agg(api_application.name, ', ') as applications FROM api_antibody LEFT JOIN api_antibodyapplications on api_antibodyapplications.antibody_id = api_antibody.ix LEFT JOIN api_application on api_application.id = api_antibodyapplications.application_id GROUP BY ix) SELECT api_antibody.ix, 'AB_' || ab_id as rrid, ab_name, accession, api_antibody.commercial_type, uid, uid_legacy, catalog_num, catalog_num_search, cat_alt, api_vendor.vendor as vendor_name, api_vendor.vendor || ' Cat# ' || catalog_num || ', RRID:AB_' || ab_id AS proper_citation, url, ab_target, ab_target_entrez_gid, uniprot_id, target_species_raw, target_subregion, target_modification, applications_subquery.applications, epitope, api_specie.name as source_organism, clonality, clone_id, product_isotype, product_conjugate, defining_citation, product_form, comments, kit_contents, feedback, curator_comment, disc_date, status, insert_time, lastedit_time, curate_time, api_antibody.show_link FROM api_antibody LEFT JOIN api_vendor on api_vendor.id = vendor_id LEFT JOIN api_specie on api_specie.id = api_antibody.source_organism_id LEFT JOIN applications_subquery on applications_subquery.ix = api_antibody.ix WHERE true"

sentry:
  sample_rate: 1.0
  traces_sample_rate: 0.05
  traces_sample_rate_resources: 0.001
  traces_sample_rate_patterns:
    "/api/": 0.05
    "/admin/": 0.002
scicrunch:
  cronjob:
    schedule: "0 1 * * 6"  # for weekend
    max_requests_per_second: 10
