harness:
  subdomain: www
  secured: open
  sentry: true
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    replicas: 2
    port: 8080
  livenessProbe:
    path: /api/live
  readinessProbe:
    path: /api/ready
  dependencies:
    build:
      - cloudharness-django
    hard:
      - common
      - events
      - accounts
      - argo
    soft:
      - pgadmin
      - accounts-api
  use_services:
    - name: common
    - name: accounts_api
  uri_role_mapping:
    - uri: /admin/*
      roles:
        - administrator
    - uri: /admin
      roles:
        - administrator
      require-any-role: true
    - uri: /add
      roles: []
      require-any-role: true
    - uri: /submissions
      roles: []
      require-any-role: false
    - uri: /login
      roles: []
      require-any-role: true
    - uri: /
      white-listed: true

  database:
    auto: true
    type: postgres
    size: 40Gi
    postgres:
      image: postgres:13
      initialdb: antibody_registry
    resources:
      requests:
        memory: 1Gi
        cpu: 200m
      limits:
        memory: 4Gi
  accounts:
    roles:
      - administrator
      - manager
      - user
  test:
    e2e:
      enabled: true

export_query: "SELECT 'AB_' || ab_id as rrid, ab_name, catalog_num, cat_alt, api_vendor.vendor as vendor_name, api_vendor.vendor || ' Cat# ' || catalog_num || ', RRID:AB_' || ab_id AS proper_citation from api_antibody LEFT JOIN api_vendor on api_vendor.id = vendor_id WHERE true"

sentry:
  sample_rate: 1.0
  traces_sample_rate: 0.05
  traces_sample_rate_resources: 0.001
  traces_sample_rate_patterns:
    "/api/": 0.05
    "/admin/": 0.002