apiVersion: batch/v1
kind: CronJob
metadata:
  name: scicrunch-citation
spec:
  schedule: "{{ .Values.apps.portal.scicrunch.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scicrunch-citation
            image: {{ .Values.apps.portal.image }}
            imagePullPolicy: IfNotPresent
            command:
            - python 
            - manage.py 
            - scicrunch_citation
            env:
            - name: CH_CURRENT_APP_NAME
              value: {{ .Values.apps.portal.harness.name | quote }}
              {{- include "deploy_utils.env" .root | nindent 8 }}
              {{- include "deploy_utils.privenv" .root | nindent 8 }}
              {{- if .Values.apps.portal.harness.env }}
                {{- .Values.apps.portal.harness.env | toYaml | nindent 8 }}
              {{- end }}
            volumeMounts:
            - name: cloudharness-allvalues
              mountPath: /opt/cloudharness/resources
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: cloudharness-allvalues
            configMap:
              name: cloudharness-allvalues
