apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: {{ .Values.apps.portal.scicrunch.cronjob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: {{ .Values.apps.portal.deployment.image }}
            imagePullPolicy: IfNotPresent
            command:
            - python 
            - manage.py 
            - scicrunch_import
            env:
            - name: CH_CURRENT_APP_NAME
              value: {{ .Values.apps.portal.harness.name | quote }}
              {{- include "deploy_utils.env" .root | nindent 8 }}
              {{- include "deploy_utils.privenv" .root | nindent 8 }}
              {{- if .Values.apps.portal.harness.env }}
                {{- .Values.apps.portal.harness.env | toYaml | nindent 8 }}
              {{- end }}
          restartPolicy: OnFailure
          volumeMounts:
          - name: cloudharness-allvalues
            mountPath: /opt/cloudharness/resources
            readOnly: true
    volumes:
        - name: cloudharness-allvalues
          configMap:
            name: cloudharness-allvalues